site_name: Metadata Migrate and Sync

site_url: https://mydomain.org/mysite

repo_name: metadata_migrate_doc
repo_url: https://github.com/esgf-us2/metadata_migrate_sync


theme:
   name: material
   palette:
      - media: "(prefers-color-scheme: light)"
        scheme: default
        primary: custom
        accent: light green
        toggle:
          icon: material/desk-lamp-off
          name: Switch to dark mode

      # Palette toggle for dark mode
      - media: "(prefers-color-scheme: dark)"
        scheme: slate
        primary: custom
        accent: light green
        toggle:
          icon: material/desk-lamp-on
          name: Switch to light mode


extra_javascript:
  - https://unpkg.com/tabulator-tables@6.3.1/dist/js/tabulator.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js


extra_css:
  - https://unpkg.com/tabulator-tables@6.3.1/dist/css/tabulator_bootstrap5.min.css
  - stylesheets/extra.css

# extensions
markdown_extensions:
   - abbr
   - meta
   - admonition # callouts/annotations
   - pymdownx.emoji:
        emoji_generator: !!python/name:material.extensions.emoji.to_svg
        emoji_index: !!python/name:material.extensions.emoji.twemoji
   - toc:
        permalink: true
   - md_in_html
   - attr_list
   - pymdownx.snippets:
        auto_append:
          - includes/glossary.md
   - def_list
   - pymdownx.details # add collapsible call-outs
   - footnotes
   - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
   - pymdownx.tabbed:
        alternate_style: true



# plugins
plugins:
   - social:
        cards_layout_options:
           font_family: Raleway
   - search
   - include-markdown:
        encoding: ascii
        preserve_includer_indent: true
        dedent: false
        trailing_newlines: false
        comments: true
        rewrite_relative_urls: true
        heading_offset: 0
        start: <!--start-->
        end: <!--end-->
        recursive: true

nav:  
   - About:
       - index.md


